project:
  type: manuscript

execute:
  freeze: auto
manuscript: 
  article: relatorio.qmd

format:    
  html:
    css: styles.css
    toc: true
    toc-depth: 3
    section-numbering: 1.1.a
    number-depth: 3
    fig-column: margin
    reference-location: margin
  typst-pdf:
    keep-typ: true
    toc: true
    toc-depth: 3
    section-numbering: 1.1.a
    number-depth: 3
    papersize: a4
    margin:
      right: 1cm
      left: 5cm
      top: 1.5cm
      bottom: 1.5cm

