project:
  type: manuscript

execute:
  freeze: auto
manuscript: 
  article: relatorio.qmd

format:    
  html:
    css: styles.css
    toc: true
    toc-depth: 3
    section-numbering: 1.1.a
    number-depth: 3
    fig-column: margin
    reference-location: margin
    comments:
      hypothesis: true
  desid-report-typst:
    keep-typ: true
    toc: true
    toc-depth: 1
    section-numbering: 1.1.a
    number-depth: 3

